# Generated by Django 4.1.1 on 2022-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
