# Generated by Django 4.1.1 on 2022-09-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_local_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem_local',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
