# Generated by Django 4.1.1 on 2022-09-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_local_imagem_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='user',
            new_name='usuario',
        ),
    ]
