# Generated by Django 4.1.1 on 2022-11-08 00:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_local_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem_local',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Local.path_imagem),
        ),
    ]
