# Generated by Django 4.1.1 on 2023-02-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_local_created_at_local_updated_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
    ]
