# Generated by Django 4.1.1 on 2023-02-01 02:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_objeto_entregue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='dono_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='dono_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem_objeto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Objeto.path_imagem),
        ),
    ]
