# Generated by Django 4.1.1 on 2023-03-31 02:15

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_objeto_dono_cpf_alter_objeto_dono_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='dono_cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True),
        ),
    ]
